lint.select = [
    "ALL"
]

lint.ignore = [
    "ANN101",   # Type annotation for self in method
    "D100",     # Missing docstring in public module
    "D104",     # Missing docstring in public package
    "D107",     # Missing docstring in `__init__`
    "D203",     # 1 blank line required before class docstring
    "D212",     # Multi-line docstring summary should start at the first line
    "PTH118",   # `os.path.join()` should be replaced by `Path` with `/` operator
    "TD002",    # Missing author in TODO
    "TD003",    # Missing issue link on the line following this TODO
]

line-length = 120

exclude = [
    ".git",
    "__pycache__",
    "env",
    ".env",
    "venv",
    ".venv",
    "build",
    "dist"
]

[lint.per-file-ignores]
# Rules that not appicable for tests:
"tests/**/*.py" = [
    "ANN201",   # Missing return type annotation for public function
    "D103",     # Missing docstring in public function
    "S101",     # Use of `assert` detected
    "PT023",    # Use `@pytest.mark.x()` over `@pytest.mark.x`
]